call plug#begin('~/.vim/plugged')
  Plug 'chriskempson/base16-vim'          " Color scheme
  Plug 'sheerun/vim-polyglot'             " More syntax highlighting
  Plug 'scrooloose/nerdtree'              " File system explorer
  Plug 'ctrlpvim/ctrlp.vim'               " Fuzzy file search
  Plug 'w0rp/ale'                         " Async lint engine
  Plug 'skywind3000/asyncrun.vim'         " Async shell commands
  Plug 'vim-airline/vim-airline'          " Status bar
  Plug 'vim-airline/vim-airline-themes'   " Status bar themes
call plug#end()                           " Initialize plugin system

" Display Settings
" ================
set encoding=utf8                         " UTF8
set t_Co=256                              " Enable 256 colors
syntax enable                             " Syntax highlighting on
  
" Color scheme
" ============
colorscheme base16-eighties

" General config
" ==============
set number                                " Line numbers
set backspace=indent,eol,start            " Allow backspace
set showcmd                               " Show cmd 
set showmode                              " Show current mode
set laststatus=2                          " Show status line
set autoread                              " Auto refresh any files that haven't been edited by Vim

" Turn off Swap files
" ===================
set noswapfile                            " Disable .swp files
set nobackup                              " Disable backup files
set nowritebackup                         " Nope
set backupdir=~/vimtmp,.                  " Write backup here
set directory=~/vimtmp,.                  " Or here

" Indentation and display
" =======================
filetype plugin on                        " Filetype detection
filetype indent on                        " Enable loading the indent file 
set autoindent                            " Automatic indentation
set tabstop=2                             " Control the number of spaces
set shiftwidth=2                          " Number of spaces for indentation
set expandtab                             " Insert spaces when tab is pressed
set softtabstop=2                         " Treat the spaces like a tab
set colorcolumn=80                        " Show a marker at 80 chars

" NERDTree
" ========
map <C-n> :NERDTreeToggle<CR>

" Fuzzy file search
" =================
let g:ctrlp_custom_ignore = 'node_modules'

" Ale
" ===
let g:ale_sign_error = '•'                " Less aggressive

" Airline
" =======
let g:airline_powerline_fonts = 0
let g:airline_theme ='base16_eighties'

" Autoformatting
" ==============
autocmd BufWritePost *.js AsyncRun -post=checktime ./node_modules/.bin/eslint --fix %

" Habit breaking, habit making
" ============================
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
