call plug#begin('~/.vim/plugged')
  Plug 'arcticicestudio/nord-vim'         " Color scheme
  Plug 'sheerun/vim-polyglot'             " More syntax highlighting
  Plug 'ctrlpvim/ctrlp.vim'               " Fuzzy file search
  Plug 'w0rp/ale'                         " Async lint engine
  Plug 'skywind3000/asyncrun.vim'         " Async shell commands
  Plug 'vim-airline/vim-airline'          " Status bar
  Plug 'vim-airline/vim-airline-themes'   " Status bar themes
  Plug 'tpope/vim-commentary'             " Comment stuff out
  Plug 'tpope/vim-surround'               " Manipulate various surroundings
  Plug 'Raimondi/delimitMate'             " Autocomplete quotes, brackets etc.
call plug#end()                           " Initialize plugin system

" Display Settings
" ================
set encoding=utf8                         " UTF8
set t_Co=256                              " Enable 256 colors
syntax enable                             " Syntax highlighting on
  
" Color scheme
" ============
colorscheme nord

" General config
" ==============
set number                                " Line numbers
set backspace=indent,eol,start            " Allow backspace
set showcmd                               " Show cmd 
set showmode                              " Show current mode
set laststatus=2                          " Show status line
set autoread                              " Auto refresh any files that haven't been edited by Vim
set clipboard^=unnamed,unnamedplus        " Enable clipboard

" Turn off Swap files
" ===================
set noswapfile                            " Disable .swp files
set nobackup                              " Disable backup files
set nowritebackup                         " Nope
set backupdir=~/vimtmp,.                  " Write backup here
set directory=~/vimtmp,.                  " Or here

" Indentation and display
" =======================
filetype plugin on                        " Filetype detection
filetype indent on                        " Enable loading the indent file 
set autoindent                            " Automatic indentation
set tabstop=2                             " Control the number of spaces
set shiftwidth=2                          " Number of spaces for indentation
set expandtab                             " Insert spaces when tab is pressed
set softtabstop=2                         " Treat the spaces like a tab
set colorcolumn=80                        " Show a marker at 80 chars

" CtrlP 
" =================
let g:ctrlp_custom_ignore = 'node_modules'

" Ale
" === 
nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)
let g:ale_sign_error = '•'                " Less aggressive
let g:ale_set_highlights = 0              " Disable highlights
let g:ale_linters = {
\  'javascript': ['standard'],
\}

" Airline
" =======
let g:airline_powerline_fonts = 0
let g:airline#extensions#ale#enabled = 1

" Autoformatting
" ==============
autocmd BufWritePost *.js AsyncRun -post=checktime npx standard --fix %

" Habit breaking, habit making
" ============================
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
